Feat: 회원가입 페이지 추가
Project-Catcher/catcher-web pull request #11
Opened 2023-10-22 04:00 UTC by pepperdad

# 변경사항
> 회원가입 페이지 - 서비스 약관 동의, 회원가입 완료 
- Greeting, Agreement, ScrollContent, Button, Checkbox 컴포넌트 추가
- 회원가입 페이지 구현 

# 테스트
- localhost:3000/signup접근
- 스토리북 추가 예정

# TODO
- 내부 스크롤 시 우측 스크롤 색 변경 필요
- alert 공통 컴포넌트의 alert으로 변경 필요
- 회원가입 완료 시, 라우팅 구현 필요
- 약관동의 체크박스 간격 조절 필요
- 클래스 공통화 작업 필요

2023-10-22 12:04 UTC, NacreousCloud requested changes
코멘트 남겨놨습니다! 확인해보시고 수정 한번 부탁드릴게요!

2023-10-22 12:04 UTC, NacreousCloud commented on src/signup/Agreement.tsx
> +    // TODO: 공통 컴포넌트의 모달로 변경
[Lv2] 공통 컴포넌트로 변경할 예정이라면 해당 상태를 단순 `boolean`의 모음으로 하는것보단 하단의 `termsOfService` 구조처럼 필수/선택의 유무를 같이 파악할 수 있게 하면 좋을것같습니다! 그렇게 하면 하단에 조건문도

```typescript
if(Object.values(agreements).every(({essential, checked}) => essential ? checked : `true`))
```

 이 한줄로 대체가능할것같기도 합니다!

2023-10-22 12:04 UTC, NacreousCloud commented on src/signup/Agreement.tsx
> +            checked={allAgreements}
[Lv2] 전체약관 동의는 모든 약관이 클릭 되어있을때만 체크되는것이 자연스러워보일것같습니다!
만약 전체약관 동의를 체크한뒤, 다른 체크박스 하나를 체크해제한다면, 전체약관동의 체크박스도 체크해제되는것이 나을것같은데 어떻게 생각하시나요??

2023-10-22 12:10 UTC, pepperdad commented on src/signup/Agreement.tsx
> +    // TODO: 공통 컴포넌트의 모달로 변경
감사합니다! 확인 후 수정하겠습니다 🔥

2023-10-22 12:12 UTC, pepperdad commented on src/signup/Agreement.tsx
> +            checked={allAgreements}
네! 저도 동일한 로직으로 구현려고 했는데 빠졌네요!
확인 후 수정하도록 하겠습니다!

2023-10-26 16:26 UTC, NacreousCloud approved these changes

2023-10-26 16:27 UTC, NacreousCloud approved these changes
확인했습니다~ 고생하셨어요!

2023-10-27 07:02 UTC, Choi-Jinwook approved these changes
확인했습니다!! 고생하셨습니다ㅎㅎ

2023-10-27 07:02 UTC, Choi-Jinwook commented on src/signup/Agreement.tsx
> +  };
저는 약관 동의 시 주로 전체 약관 동의를 누른 다음 선택부분을 체크해제하는데요
이 때 전체 약관 동의 부분의 체크가 해제되는게 보편적이더라구요
그래서 전체 약관 동의를 누른 후에 일부 약관에 대해 체크해제하는 동작에 대한 처리가 있으면 좋을 것 같습니다!
useEffect를 사용해서 개별 체크박스에 대해 변화가 생겼을 경우 setAll~을 핸들링하는 방식은 어떨까요??

2023-10-27 15:45 UTC, merged