Feat/login
Project-Catcher/catcher-web pull request #12
Opened 2023-10-22 10:36 UTC by Choi-Jinwook

## 🏷️ 로그인 및 아이디/비밀번호 화면 구현
- 화면 자체만 구현했습니다
- api 연동 및 캡차 적용은 **_명세서 나오고 / 캡차 api 및 이메일 인증 api 정해진 후_** 적용 예정입니다

## ✅ 적용사항
- login 페이지에서 아이디 찾기 / 비밀번호 재설정 클릭 시 findid페이지로 라우팅 세팅해놨습니다.

- 마찬가지로 비밀번호 찾기 프로세스 완료 시 로그인 버튼 클릭하면 login 페이지로 라우팅 세팅해놨습니다.
- 비밀번호 재설정의 경우 추후 아이디 확인이 필요없는 경우를 위해 queryParams로 비밀번호 재설정 프로세스의 단계를 선택해서 라우팅 할 수 있게 했습니다.
- custom hook으로 정규식 세팅해놨습니다(한글이름, 휴대폰(11자리), 아이디, 비밀번호). **_필요하신 경우 가져다 쓰시면 될 것 같습니다._**
- 각 프로세스에서 정규식 조건을 충족하지 못했을 시 버튼 비활성화 처리해놨습니다.
- 이름, 전화번호(이메일) 입력 후 인증 요청 시 readOnly 세팅해놨습니다.
- 비밀번호 표시는 마우스를 꾹 누르고 있을 때 적용되게 했습니다.

## 🤔 생각해야 될 부분
- 현재 인증 시 이름 입력이 한글 2~4자리만 가능함. 영어 이름이나 특이한 이름의 경우에는 어떻게 처리할지
- findid 페이지의 이름(findaccount 생각중인데 더 좋은 네이밍 추천부탁드립니다!)
- 주석?
- 이미지 파일 형식(png? svg?) 및 이미지를 코드에서 직접 import 하는것과 public 폴더 속 경로로 불러오는 것의 차이

2023-10-23 16:18 UTC, NacreousCloud requested changes
확인했습니다! 코멘트 한번씩 확인 부탁드리겠습니다ㅎㅎ 고생많으셨어요!

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/AccountFind.tsx
> +    (query.type as LoginType) || "id",
[Lv2] 넘어오는 데이터가 nullish 하기 때문에 `OR 연산자`를 사용하신거라면  대신 `널 병합 연산자` (`??`)를 사용하는것도 좋을것같습니다!

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/FindIdForm.tsx
> +  const [isChecked, setIsChecked] = useState<Checked>({
[Lv3] `Checked` 라는 명칭은 interface 명을 보고 어떤걸 체크하는건지 확인이 어려울것같습니다! 구체적으로 작성이 되면 좋겠습니다ㅎㅎ
또 interface가 여기에서만 사용되고있는것같은데 전체에서 사용될일이 없다면 이 파일 내로 가져오는것도 좋을것같습니다!

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/IdCheck.tsx
> +      "아이디 확인 후 비밀번호를 재설정 할 수 있습니다.",
[Lv2] 이부분은 useMemo를 사용하신 이유가 있으실까요? 스트링 배열로 넘겨주기만 하면 된다면 단순 상수 배열로만 넘겨줘도되지않을까 싶어서 질문드립니다ㅎㅎ

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/AuthenticationBox.tsx
> +          }) => {
[Lv3] 해당 `children` 객체가 여기 있어야할 이유가 있을까요? 이곳에서 받아야하는 데이터는 `type` 뿐인것같은데 이건`AuthenticationForm` 에서 이미 받고 있다보니 굳이 이곳에 있지않아도될것같습니다!

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/AuthenticationBox.tsx
> +                      인증 성공!
[Lv2] `인증 성공` 이 렌더링되는 조건도 들어가야할것같습니다!

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/AuthenticationBox.tsx
> +              : "본인확인 이메일 주소와 입력한 이메일 주소가 같아야, 인증번호를 받을 수 있습니다."
이 파일 내에서 `isPhone`으로 분기처리되는 문자열이 두개가 있어서 적용하긴 조금 애매하긴한데, 이렇게 분기처리되는게 많아진다면 문자열들을 하나의 객체로 만들어서 관리하는것도 가독성 향상에 도움이 될 수 있어서 말씀드립니다!

예시)
```typescript
  const messages = {
    phone: {
      authMethodLabel: "휴대전화로 인증하여 찾기",
      authFormDescription:
        "회원정보에 등록한 휴대전화 번호와 입력한 휴대전화 번호가 같아야 인증번호를 받을 수 있습니다.",
    },
    email: {
      authMethodLabel: "이메일로 인증하여 찾기",
      authFormDescription:
        "본인확인 이메일 주소와 입력한 이메일 주소가 같아야, 인증번호를 받을 수 있습니다.",
    },
  };

//  label={messages[type].authMethodLabel}
//  description={messages[type].authFormDescription}
```

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/AuthenticationForm.tsx
> +  const [answer, setAnswer] = useState<AnswerType>({});
[Lv3] AnswerType은 사실상 string 키에 대응하는 모든 데이터를 받는걸로 보입니다. 이렇게되면 개발 진행하면서 key 값에 오타가 발생한다해도 인지하지못하고 넘어갈 수 도 있기때문에 form에서 사용되는 타입은 번거롭더라도 명시해서 작업하시는게 좋을것같습니다!

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/AuthenticationForm.tsx
> +            onChange={({ currentTarget: { value } }) =>
이건 개인적인 취향이긴한데, return 되는 html 구문내에서 onHandler 익명메소드를 직접 작성하는것보단, 별도의 함수를 만들어서 그냥 대입하는게 깔끔해보일것같습니다!
이건 취향차이라서 편하신대로 진행하셔도 좋을것같습니다ㅎㅎ

```
// 함수 영역
  const handleNameChange = ({
    currentTarget: { value },
  }: ChangeEvent<HTMLInputElement>) => handleName({ name: value });

// html 영역
 onChange={handleNameChange}
```

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/Instructions.tsx
> +  const [isHover, setIsHover] = useState<boolean>(false);
initial 값이 있다면 useState에 굳이 타입을 명시할 필요는 없습니다!

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/ModeButton.tsx
> +        if (target instanceof HTMLButtonElement)
[Lv2] target 의 id를 가져오지 못해서 이렇게 작성하신거라면, onClick 이벤트 파라미터의 타입을 지정해줌으로 수정하실수있습니다!

```typescript
onClick={({ currentTarget }: MouseEvent<HTMLButtonElement>) => {
  handleMode(currentTarget.id as LoginType);
}}
```

2023-10-23 16:18 UTC, NacreousCloud commented on src/findid/components/PasswordResetForm.tsx
> +  const handleAnswer = (answer: AnswerType) => {
[Lv2] 여기도 아까 코멘트 단것처럼 form에서 사용되는 interface를 따로 명시해주면 좋을것같습니다!

2023-10-23 16:18 UTC, NacreousCloud commented on src/login/components/LoginForm.tsx
> +        query: { type: type },
[Lv2] 속성명과 변수명이 같다면 굳이 따로 적지않아도 입력이 가능합니다!

`query: { type }`

2023-10-23 16:18 UTC, NacreousCloud commented on src/shared/components/CaptchaWithButton.tsx
> +        isValidate={(isValidate[type] && isValidate.name) as boolean}
[Lv2] `isValidate`의 속성을 한쪽은 [] 으로 쓰고 한쪽은 . 으로 쓰신 이유가 있을까요??

2023-10-23 16:18 UTC, NacreousCloud commented on src/shared/components/CaptchaWithButton.tsx
> +        isValidate={(isValidate[type] && isValidate.name) as boolean}
추가로 isValidate도 `AnswerType` 으로 지정되어서 boolean이 확실함에도 타입 단언을 해줘야하는 상황이 나오고있습니다! 여기도 타입을 별도로 작성해주시는게 좋을것같아요

2023-10-23 16:37 UTC, Choi-Jinwook commented on src/findid/components/IdCheck.tsx
> +      "아이디 확인 후 비밀번호를 재설정 할 수 있습니다.",
map에 사용되는 배열은 useMemo로 감싸주는게 좋다고 배웠는데 단순 문자열 배열은 useMemo를 쓰는게 오히려 악영향을 미칠까요??

2023-10-23 17:02 UTC, Choi-Jinwook commented on src/findid/components/AuthenticationBox.tsx
> +          }) => {
처음에 인증번호 받기를 눌렀을 때 캡차 부분이 사라지고 인증번호 입력 인풋으로 바뀌기 때문에 children 객체에 담는것을 생각했는데요
AnswerType에 캡차 상태까지 다 때려박고 생각을 하다보니 매몰된 부분인 것 같습니다!
캡차 관련 상태를 나누고 생각해보니 굳이 필요없을 것 같네요😀

2023-10-23 17:37 UTC, Choi-Jinwook commented on src/findid/components/AuthenticationBox.tsx
> +                      인증 성공!
이 부분은 기획이랑 디자인 측에서 확인이 필요한 부분이 있는데 안내문구가 나와야 하는것은 동일하니 조건 추가하겠습니다!

2023-10-23 17:44 UTC, Choi-Jinwook commented on src/shared/components/CaptchaWithButton.tsx
> +        isValidate={(isValidate[type] && isValidate.name) as boolean}
isValidate가 useRegex hook에서 나온건데
useRegex 안에 정규식이 필요한 모든 함수를 다 때려넣었습니다. 그래서 이름, 아이디, 비밀번호, 이메일, 전화번호 등등에 대한 체크가 필요한 상황인데요
`interface RegexValidationType {
  id: boolean;
  phone: boolean;
  email: boolean;
}
  const [isValidate, setIsValidate] = useState<RegexValidationType>({ id: false, phone: false, .... });`
이런 식으로 진행하자니 isValidate 객체에서 불필요한 값들까지 가져오게 되었습니다.
?: 를 사용하자니 undefined때문에 ?. 조건식을 추가해야 해서 그렇게 좋은 방법은 아닌 것 같은데
혹시 [key: string]: boolean 말고 isValidate 객체 안에 선택적으로 필요한 Key만 string으로 담을 방법은 없을까요??

2023-10-25 02:19 UTC, pepperdad commented on src/findid/components/AccountFind.tsx
> +    <WhiteBox
이 WhiteBox 컴포넌트에서 style 값들을 각자 prop 들을 따로 넘기고 있는데, tailwind가 className에 스타일이 string으로 들어가기 때문에 boxStyle 이란 prop 하나로 합치는게 좋아보입니다! 

```typescript
boxStye='w-[705px] h-[710px] px-[69.5px] py-[33px] shadow-[0_4px_35px_0_rgba(0,0,0,0.08)]' 
```
이렇게요!

2023-10-25 02:20 UTC, pepperdad commented on src/shared/components/WhiteBox.tsx
> +        className={`${boxWidth} ${boxHeight} ${radius} ${paddingX} ${paddingY} ${shadow}`}
그리고 여기서 받을 때,
```typescirpt
 className={`${boxStyle}'} 
 ```
 이렇게 prop 하나로요!

2023-10-25 02:27 UTC, pepperdad requested changes
확인했습니다! 앞으로 더 열심히 리뷰하려고 노력하겠습니다 :))
고생하셨습니다!

2023-10-25 12:04 UTC, Choi-Jinwook commented on src/findid/components/AccountFind.tsx
> +    <WhiteBox
자꾸 tailwind 장점을 활용을 못하네요😂
혹시 리뷰 남기실 때 까만 박스에 코드 넣는건 어떻게 하신건지 깃헙에서 인용이 힘들면 swit으로 알려주실 수 있으실까요?!

2023-10-25 12:37 UTC, Choi-Jinwook commented
리뷰 사항들 변경하려 했는데 변경하다보니
이전 비밀번호 찾기 프로세스에서는 PasswordResetForm이 progress 1,2 모두 렌더링되었기 때문에 id에 대한 값이 날아가버렸습니다.
이 부분 수정해서 비밀번호 찾기 프로세스 1,2 모두 완료했을 때 백엔드 서버에 id와 변경된 pw를 줄 수 있게 개선했습니다.
추가적인 사항들 한 번에 하나씩 커밋하겠습니다...!

2023-10-25 13:22 UTC, NacreousCloud commented on src/findid/components/IdCheck.tsx
> +      "아이디 확인 후 비밀번호를 재설정 할 수 있습니다.",
과도한 계산이 있지않다면 useMemo를 사용할 필요는 없습니다! 단순 렌더링을 할때는 성능에 영향이 있을정도가 아니기때문에 굳이 사용하지는 않는 편입니당

2023-10-25 13:22 UTC, NacreousCloud commented on src/findid/components/IdCheck.tsx
> +      "아이디 확인 후 비밀번호를 재설정 할 수 있습니다.",
과도한 계산이 있지않다면 useMemo를 사용할 필요는 없습니다! 단순 렌더링을 할때는 성능에 영향이 있을정도가 아니기때문에 굳이 사용하지는 않는 편입니당

2023-10-25 13:46 UTC, NacreousCloud commented on src/shared/components/CaptchaWithButton.tsx
> +        isValidate={(isValidate[type] && isValidate.name) as boolean}
이 구조를 유지하신다면 이대로 사용하시는게 나을것같지만, 제 개인적인 생각으로 권장 드리자면 hook 구조를 떠나서 각각 일반 util 함수로 두는게 나을것같습니다..!
이유는 다음과 같습니다

1. hook에 다 때려넣었기 때문에 딱 하나의 정규식 실행을 위해 필요없는 함수들을 가져오게된다.
    - util로 분리하면 필요할때마다 하나씩 사용이 가능하다
3. 정규식 자체의 성능이 그렇게 영향을 주지않기 때문에 useCallback을 사용할 필요가 없다.
4. returnType 명명이 간단해진다

이러한 이유로 한번 제안드려봅니다!

2023-10-25 14:36 UTC, Choi-Jinwook commented on src/shared/components/CaptchaWithButton.tsx
> +        isValidate={(isValidate[type] && isValidate.name) as boolean}
오 굉장히 간결해졌습니다ㅎㅎ 어차피 값이 변할때마다 리렌더링되니까 쓸모없는 useEffect도 사라져서 좋네요

2023-10-27 02:01 UTC, NacreousCloud requested changes
확인했습니다~ 어제 채팅으로 전달드린 충돌관리와, 추가적인 코멘트 확인만 하고 머지 진행하도록 하죠!
고생많으셨습니다!

2023-10-27 02:01 UTC, NacreousCloud commented on index.html
[Lv2] 이 파일은 테스트용인가요?? 그냥 봤을때 다른 파일이 딸려들어온것같은데 지워두셔야할거같습니다~

2023-10-27 02:01 UTC, NacreousCloud commented on src/findid/components/AuthErrorMessage.tsx
> +    </>
```suggestion
    <div className="text-[#FF2330] mt-[5px] mb-[12px]">
       {isExpired ? "인증번호를 다시 요청해주세요." : "발송된 인증번호를 확인해주세요."}
    </div>
```
[Lv2] 해당 리턴 컴포넌트는 내용값만 다른것같아서 이렇게 줄일수있을것같습니다!

2023-10-27 02:01 UTC, NacreousCloud commented on src/findid/components/PasswordResetProgress.tsx
> +          {({ handleId, handleNewPassword, handleCheckNewPassword }) => (
[Lv2] 내부 children에 들어가는 함수가 여기에 있을필요는 없어보입니다! PasswordResetForm 내부에 그냥 넣어도될것같은데 어떻 게 생각하시나요?

2023-10-27 02:01 UTC, NacreousCloud commented on src/findid/components/AccountFind.tsx
> +  );
[Lv2] `useCallback ` 을 사용하는 이유가 있을까요? 다른 파일의 `push` 함수에는 없는것같은데 별다른 이유가 없다면 빼셔도 좋을거같습니다

2023-10-27 03:40 UTC, Choi-Jinwook commented on index.html
아 이거 과제인데 터미널에서 연결된 흔적이 없는데 왜 들어갔는지 모르겠네요.. 삭제하겠습니다!

2023-10-27 03:41 UTC, Choi-Jinwook commented on src/findid/components/AccountFind.tsx
> +  );
다른 파일의 push 함수는 props로 내려주는게 아니라서 `useCallback`을 사용하지 않았습니다!
prop drilling이 일어나는 함수들은 최적화 면에서 useCallback으로 감싸주는 것이 좋은 것으로 알고 있는데 혹시 틀린 부분이 있을까요?

2023-10-27 03:46 UTC, Choi-Jinwook commented on src/findid/components/PasswordResetProgress.tsx
> +          {({ handleId, handleNewPassword, handleCheckNewPassword }) => (
`PasswordResetProgress` 컴포넌트에서 각 `currentProgress` 값에 대해 어떤 컴포넌트가 보여질지에 대해 한 눈에 파악하려고 이렇게 설계했는데 인증 단계가 들어가면서 오히려 가독성을 해치게 된 것 같습니다! 이 부분 수정해서 커밋하겠습니다

2023-10-27 12:16 UTC, NacreousCloud commented on src/findid/components/AccountFind.tsx
> +  );
음 사실 전 크게 영향을 준다고 생각이 들진않습니다! 애초에 useCallback을 쓸정도로 최적화가 필요한 상태는 아니라고 보기도하고,
오히려 useCallback을 사용하면 사이드이펙트가 발생할 확률이 있기때문에 사용을 지양하는편입니다
최적화는 어느정도 기능 구현이 된 이후 생각해보면 어떨까요??

2023-10-27 12:21 UTC, Choi-Jinwook commented on src/findid/components/AccountFind.tsx
> +  );
넵 수정해서 커밋하겠습니다!

2023-10-27 12:26 UTC, NacreousCloud approved these changes
확인했습니다! 고생많으셨어요!

2023-10-27 15:45 UTC, pepperdad approved these changes
확인했습니다! 고생하셨습니다 ㅎㅎ

2023-10-27 16:04 UTC, merged