Feat: 공지사항 및 FAQ 페이지 추가
Project-Catcher/catcher-web pull request #25
Opened 2023-10-30 15:32 UTC by Choi-Jinwook

## 구현사항
- Figma 공지사항 및 약관 1,2 페이지
- 모든 페이지네이션은 임시로 박아놓은 것이며 클릭 이벤트 외 아무 기능이 없음
## 테스트
- http://localhost:3000/notice
- http://localhost:3000/notice/faq
## TODO
- 검색 기능
- 카테고리(전체, 이벤트 등) 선택에 따른 컨텐츠 재구성
- 공용 페이지네이션
## 생각할 부분
- 좌측 상단 Home 아이콘은 기능이 있는건지
- 태그는 어떤 용도인지(태그로 검색이 가능한가)
- 페이지네이션을 공용으로 만들기(RQ, Recoil, props)

2023-11-01 17:53 UTC, NacreousCloud requested changes
코멘트 확인 부탁드립니다~!

2023-11-01 17:53 UTC, NacreousCloud commented on src/shared/styles/globals.css
[Lv3] 여기있는 주석들은 지워야합니다! 현재 develop과 충돌이 날거라 미리 pull받아서 충돌관리를 해두는게 좋을것같습니다.

2023-11-01 17:53 UTC, NacreousCloud commented on src/notices/faq/components/FAQContent.tsx
> +  const [isOpen, setIsOpen] = useState(["q-1"]);
[Lv2] state 내용물이 배열 형태라면 변수명이 is~ 로 시작하는건 헷갈리기 쉬울것같습니다 (보통 is~ 로 시작하는건 boolean 타입이기 때문)

openState 같은 형식으로 바꾸는건 어떨까요?

2023-11-01 17:53 UTC, NacreousCloud commented on src/notices/faq/components/FAQContent.tsx
> +  const [isOpen, setIsOpen] = useState(["q-1"]);
[Lv2] 배열 내부 데이터가 q-1 같은 string 형식인 이유가 있을까요? 받은 데이터의 개수가 명확하기 때문에 array index로 구분하여 boolean으로 관리해도 좋을것같습니다

```suggestion
  const [openState, setOpenState] = useState(Array(CONTENT_COUNT).fill(false));
```
이렇게 하면 open 여부를 string으로 비교하는게 아닌 true/false로 바로 사용할수있기 때문에 코드 가독성 면에서도 유리합니다

2023-11-01 17:53 UTC, NacreousCloud commented on src/notices/faq/components/FAQContent.tsx
> +    else setIsOpen((prev) => [...prev, id]);
[Lv2] 위에서 작성한대로 true/false로 구분하는게 효율적입니다!

2023-11-01 17:53 UTC, NacreousCloud commented on pages/notice/faq.tsx
[Lv2] FAQ, Notice 전부 url 뎁스가 동일한데 notice 폴더에서 관리하는 이유가 있으실까요?
( 홈 > 공지사항 )
( 홈 > FAQ  )

이렇게되면 url이 /notice /notice/faq 이렇게 되기때문에 url 구조가 어색해보일것같습니다.

2023-11-02 01:09 UTC, Choi-Jinwook commented on src/notices/faq/components/FAQContent.tsx
> +  const [isOpen, setIsOpen] = useState(["q-1"]);
아 인덱스로 바로 접근이 가능하겠군요!! 감사합니다😀

2023-11-02 01:32 UTC, Choi-Jinwook commented on pages/notice/faq.tsx
피그마에 공지사항 및 약관 1, 2 로 나눠져있어서 이렇게 했는데 말씀 듣고보니 어색한 것 같습니다! 수정하겠습니다

2023-11-04 01:20 UTC, NacreousCloud approved these changes
확인했습니다~

2023-11-05 11:33 UTC, merged