Feat: 헤더 구현
Project-Catcher/catcher-web pull request #26
Opened 2023-10-31 05:27 UTC by pepperdad

# 구현사항
> 헤더 구현
- 로그인 여부에 따라 헤더 구현 (현재 로그인 확인 로직이 없어, 항상 비로그인 상태로 작성)
- 헤더 기본 bg는 transparent이나, 스크롤 시의 색상이 Figma에 나와있지 않아, 임시로 bg-white로 설정

# 테스트
- 모든 페이지에서 접근 가능

# TODO
- 로그인 여부 확인 로직 구현시, 수정할 것

2023-11-01 16:48 UTC, NacreousCloud requested changes
코멘트 한번씩 확인부탁드려요~

2023-11-01 16:48 UTC, NacreousCloud commented on src/shared/component/header/Notification.tsx
> +          <div className="flex-center">
[Lv2] 내부 알림 아이템도 컴포넌트로 분리하면 가독성측면에서 좋을것같습니다!

2023-11-01 16:48 UTC, NacreousCloud commented on src/shared/component/header/Tabs.tsx
> +              onClick={() => onClickToggle("notification")}
[Lv3] 기획서를 보시면 프로필+ID 영역 클릭시 토글이 되어야합니다! 이부분은 나중에 작업하시다가 누락할수도있으니 미리 수정해두시는게 좋을것같아요~

2023-11-01 16:48 UTC, NacreousCloud commented on src/shared/component/header/index.tsx
> +    setScrollPosition(window.scrollY || document.documentElement.scrollTop);
[Lv3] scrollPosition 상태를 사용하지않아도 해당 로직과 아래 useEffect 로직을 사용할수있는데  상태로 관리하시는 이유가 있을까요?? 이렇게 사용하면 스크롤할때마다 상태 업데이트가 일어나기때문에 불필요한 렌더링이 반복됩니다!

2023-11-01 16:48 UTC, NacreousCloud commented on src/shared/component/header/Tabs.tsx
> +  const [onToggle, setOnToggle] = useState("");
[Lv2] onToggle 내부 데이터가 고정된 id로 되어있다면 해당 데이터들을 타입으로 관리하는게 좋습니다!

```suggestion

  type ToggleType = "notification" | "myInfo";
  const [onToggle, setOnToggle] = useState<ToggleType>();

  const onClickToggle = (target: ToggleType) => {
    setOnToggle((prev) => (prev === target ? undefined : target));
  };
  
```

2023-11-02 05:23 UTC, pepperdad commented on src/shared/component/header/index.tsx
> +    setScrollPosition(window.scrollY || document.documentElement.scrollTop);
scrollPosition을 useState와 같은 상태를 사용하지 않고, 

```
  const updateScroll = () => {
    const scrollPosition = window.scrollY || document.documentElement.scrollTop;

    if (scrollPosition < 10) {
      // 투명한 배경색으로 처리
      setHeaderColor("transparent");
    } else {
      // 흰색 배경색으로 처리
      setHeaderColor("white");
    }
  };

  useEffect(() => {
    window.addEventListener("scroll", updateScroll);
    return () => {
      window.removeEventListener("scroll", updateScroll);
    };
  }, []);
```
이런 식으로 작성하라는 의미가 맞을까요!?

2023-11-02 05:24 UTC, pepperdad commented on src/shared/component/header/Tabs.tsx
> +              onClick={() => onClickToggle("notification")}
넵 확인했습니다 :)

2023-11-02 05:25 UTC, pepperdad commented on src/shared/component/header/Notification.tsx
> +          <div className="flex-center">
넵 확인했습니다! :)

2023-11-02 05:31 UTC, pepperdad commented on src/shared/component/header/Tabs.tsx
> +  const [onToggle, setOnToggle] = useState("");
감사합니다! 확인했습니다 :)

2023-11-02 12:10 UTC, Choi-Jinwook reviewed
확인했습니다! 코멘트 남긴 부분 확인부탁드립니다😀

2023-11-02 12:10 UTC, Choi-Jinwook commented on src/shared/component/header/MyInfo.tsx
> +        </div>
[Lv2] 이 부분 반복적인 부분이라 컴포넌트로 관리하는게 좋을 것 같습니다!!
추가적으로 내 일정에 분홍 배경은 hover 이벤트일 것 같은데 승연님과 이야기해보는게 좋을 것 같습니다!

2023-11-04 01:20 UTC, NacreousCloud commented on src/shared/component/header/index.tsx
> +    setScrollPosition(window.scrollY || document.documentElement.scrollTop);
네넵 맞습니다!

2023-11-04 05:39 UTC, pepperdad commented on src/shared/component/header/MyInfo.tsx
> +        </div>
넵! 확인했습니다 ㅎㅎ

2023-11-05 06:31 UTC, NacreousCloud approved these changes
확인했습니다. Lv2로 코멘트 달아놓은 부분들은 장기적으로 보면 이점이 많기때문에 시간나시면 한번 적용해보세용

2023-11-09 02:08 UTC, merged