Feat: 소셜 로그인 authorization code 발급 프로세스 추가
Project-Catcher/catcher-web pull request #29
Opened 2023-11-02 11:50 UTC by Choi-Jinwook

## 변경사항
- 컴포넌트 분리
- LoginOption.tsx에서 로그인 관련 함수 추가
- pages/login/kakao.tsx, naver.tsx에서 code 발급
## 테스트
- http://localhost:3000/login 에서 네이버 / 카카오 로그인 버튼 클릭
## TODO
- axios 적용
- 현재 code 발급까지는 성공, api 나온 이후 토큰 발급 프로세스 추가
- pages/login/[socialLoginType] 화면 꾸미기??
## 생각할 부분
- 현재 카카오, 네이버 로그인 시 handleLogin 함수를 넣었는데 따로 추가될 부분이 없으면 함수 빼야함

2023-11-05 07:16 UTC, NacreousCloud requested changes
고생하셨어요! 코멘트 확인 한번 부탁드립니다~

2023-11-05 07:16 UTC, NacreousCloud commented on pages/login/kakao.tsx
> +  const [userInfo, setUserInfo] = useState<any>({}); // TODO: recoil
[Lv3] 유저 정보는 recoil로 관리하면 안될것같습니다. 새로고침시 데이터가 날아가기때문인데, sessionStorage나 cookie로 관리하는게 일반적일거에요. 이부분은 아직 TODO지만 미리 확인해두시는걸 권장드립니다

2023-11-05 07:16 UTC, NacreousCloud commented on pages/login/kakao.tsx
> +  console.log("KAKAO_CODE:", KAKAO_CODE);
[Lv3] 현재 여기서 로그를 찍어보면 KAKAO_CODE가 undefined로 나오는데 진욱님도 확인되실까요? useRouter가 mounded되기전에 로그를 찍어서 나오지않는것으로 보입니다. 이럴때는 useEffect deps에 router를 추가하거나, location.search로 찾는것도 좋습니다.

2023-11-05 07:16 UTC, NacreousCloud commented on pages/login/naver.tsx
[Lv2] naver는 개발모드일때는 등록된 아이디만 사용이 가능해서 확인을 못했습니다. 하지만 구조가 동일한걸로 보아, 카카오 로그인 페이지에서 남긴 코멘트 동일하게 네이버도 해당된다고 보시면 됩니다!

2023-11-05 07:16 UTC, NacreousCloud commented on src/login/components/LoginForm.tsx
>      isChecked: false,
[Lv2] isChecked는 로그인 페이지에서 명칭만 봤을때 무엇을 체크한것인지 한번에 유추하기가 어려워보입니다. `isAutoLogin` 같이 무엇을 위한 변수인지 제대로 입력해주는것을 권장드립니다

2023-11-05 07:16 UTC, NacreousCloud commented on src/login/components/LoginError.tsx
`setIsError`는 api 호출 이후에 어디서 세팅하나요?? 구조로 봤을때 상위에서 props로 넘겨줘도 좋을것같습니다.

2023-11-05 07:16 UTC, NacreousCloud commented on pages/login/kakao.tsx
[Lv2] 그런데 로그인 후 redirection이 페이지로 와야하는 이유가 있을까요?? 디자인이나 기획에서 이러한 상황을 상정하지는 않은것 같기도하고, 로그인을 위한 code가 노출되는 셈인데, 차라리 /page/api/** 으로 넘기고 거기에서 데이터 처리후 다시 페이지 리다이렉트를 하는건 어떨까요?

2023-11-05 07:16 UTC, NacreousCloud commented on src/login/components/LoginOption.tsx
> +    if (answer.id === "" || answer.password === "") alert("빈칸이 있어요");
[Lv2] 이런 빈칸에 대한 에러나, api 호출 뒤 받는 데이터는 어떻게 띄우실지 여쭤봐도될까요? alert을 띄우게 되면 사용자가 얼럿을 한번 꺼야하는 행동이 추가되기때문에 사용자 경험에 안좋은 영향을 줄수있습니다!

2023-11-06 06:53 UTC, Choi-Jinwook commented on pages/login/kakao.tsx
> +  const [userInfo, setUserInfo] = useState<any>({}); // TODO: recoil
아 토큰만 쿠키에 저장하는게 아니고 유저정보도 쿠키로 관리하는군요!! 감사합니다😀

2023-11-06 07:02 UTC, Choi-Jinwook commented on pages/login/kakao.tsx
> +  console.log("KAKAO_CODE:", KAKAO_CODE);
```typescript
  useEffect(() => {
    const KAKAO_CODE = location.search.split("=")[1];
    console.log(KAKAO_CODE);

    if (KAKAO_CODE && !userInfo.accessToken) {
      getAccessToken();
    }
  }, [userInfo.accessToken]);
```
현재 이렇게 바꿔봤는데 이렇게 사용하는게 맞을까요??

2023-11-06 07:18 UTC, Choi-Jinwook commented on src/login/components/LoginOption.tsx
> +    if (answer.id === "" || answer.password === "") alert("빈칸이 있어요");
빈칸에 대한 에러는 얼럿으로 띄우는게 보편적이라 생각했는데 에러 메세지로 관리하는게 더 좋을 것 같습니다! 이 부분 기획팀이랑 상의해보고 진행하겠습니다!
api호출 뒤 받는 데이터는 유저 데이터를 저장하는 공용 유틸 함수를 만들고 쿠키에 저장할 것 같습니다! 혹시 다른 의미의 질문이셨을까요?

2023-11-06 07:22 UTC, Choi-Jinwook commented on pages/login/kakao.tsx
이 부분은 처음 해보는거라 잘 모르기도 하고 code가 제대로 발급되는지 확인하려고 페이지로 보냈는데 보안상으로도 위험하고 부자연스러운 것 같습니다!
혹시 /pages/api/kakao.ts로 넘긴다고 하면 페이지의 이동 없이 데이터 처리 후 리다이렉트가 가능한가요??

2023-11-06 14:47 UTC, NacreousCloud commented on pages/login/kakao.tsx
> +  console.log("KAKAO_CODE:", KAKAO_CODE);
결과값은 동일하지만 location.search를 사용할땐 가급적 `URLSearchParams` 사용을 권장드립니다!

```javascript
 useEffect(() => {
    const KAKAO_CODE = new URLSearchParams().get("code");

    if (KAKAO_CODE && !userInfo.accessToken) {
      getAccessToken();
    }
  }, []);
```

2023-11-06 14:49 UTC, NacreousCloud commented on pages/login/kakao.tsx
제 경험상 리다이렉트는 정상적으로 됐던것으로 기억합니다! 결국 프론트 내부 서버로 넘기는것이다보니 리다이렉트또한 문제는 없을것같네요

2023-11-06 14:50 UTC, NacreousCloud commented on src/login/components/LoginOption.tsx
> +    if (answer.id === "" || answer.password === "") alert("빈칸이 있어요");
아뇨 맞습니다! 기획팀과 상의후 진행 부탁드릴게요~

2023-11-10 08:22 UTC, Choi-Jinwook commented
일단 임시로 토큰 발급 프로세스, 로그아웃도 구현해놨습니다! 추후 api 개발이 완료되면 연동 예정입니다

2023-11-16 16:25 UTC, NacreousCloud approved these changes
확인했습니다~ 아래 Suggest는 중요도가 낮으니 따로 Request Changes는 넣지않았습니다! 수정하고 별 이상이 없다면 머지해주세요~ 고생하셨습니다!

2023-11-16 16:25 UTC, NacreousCloud commented on src/login/components/LoginOption.tsx
> +    push(`${KAKAO_CODE_URL}`);
```suggestion
    push(KAKAO_CODE_URL);
```

2023-11-16 16:25 UTC, NacreousCloud commented on src/login/components/LoginOption.tsx
> +    push(`${NAVER_CODE_URL}`);
```suggestion
    push(NAVER_CODE_URL);
```

2023-11-17 04:31 UTC, merged