Feat: 일정만들기 1 페이지 추가
Project-Catcher/catcher-web pull request #30
Opened 2023-11-03 07:37 UTC by pepperdad

# 구현사항
> 일정만들기 페이지
- Tab 컴포넌트 추가
- ScheduleCard 컴포넌트 추가

# 테스트
- localhost:3000/schedule/create 접근

# TODO
- 탭 전환시 동적으로 데이터 불러올지, 혹은 현재 있는 데이터에서 필터링 할지 고민할 것 
- 삭제하기 버튼 클릭시, 서버에 삭제 요청 추가

2023-11-03 08:46 UTC, Choi-Jinwook reviewed
확인했습니다! 코멘트 확인부탁드릴게요😀

2023-11-03 08:46 UTC, Choi-Jinwook commented on src/create/components/ScheduleCard.tsx
> +          )}
[Lv1] 이 부분 일정 구분이 완료, 작성 중 말고 더 있을 것 같은데 일단 임시로 해놓으신 걸까요??
기획/디자인쪽이랑 이야기해보고 컴포넌트로 관리하는것이 좋을 것 같습니다!

2023-11-04 13:41 UTC, pepperdad commented on src/create/components/ScheduleCard.tsx
> +          )}
넵 맞습니다! 이 부분은 기획/디자인 부분이랑 얘기가 필요할 것 같네요!!

2023-11-05 10:05 UTC, NacreousCloud requested changes
고생하셨어요~ 코멘트 확인 부탁드립니다~

2023-11-05 10:05 UTC, NacreousCloud commented on src/create/components/ScheduleTab.tsx
> +const tabItems = [
```suggestion
const tabItems: Record<"title", TabType>[] = [
```

[Lv2] 이렇게 하면 25번줄에 타입 단언을 쓰지않아도 사용할수있습니다.
`as Type` 형식의 타입단언은 가능하다면 최소한으로 사용하는게 디버그할때 좋습니다!

2023-11-05 10:05 UTC, NacreousCloud commented on src/create/components/Create.tsx
> +  // date, tab, title 이 바뀔 때마다 필터링 진행
[Lv3] 바뀔때마다 필터링하는 기획이 있나요?? 제가 확인해봤을땐 안보였는데, 해당 이펙트는 리소스 소모가 클것같아서 조정이 필요해보입니다. 기획팀이나 디자인팀에 문의해보죠!

2023-11-05 10:05 UTC, NacreousCloud commented on src/create/components/InputCalender.tsx
> +            onChange={(newDate: any) => handleDateChange(newDate)}
```suggestion
                    onClickDay={handleDateChange} 
```
[Lv3] Day 클릭시 발생하는 이벤트로 대체하면 any 타입 명시 없이 사용가능합니다.
타입단언만큼, any 타입의 사용도 최소한으로 사용하는것이 좋습니다!

2023-11-05 10:05 UTC, NacreousCloud commented on src/create/components/Create.tsx
> +          card.title.toLowerCase().includes(title.toLowerCase())
```suggestion
          
      if (!card.title.toLowerCase().includes(title.toLowerCase())) return false;
      
```
중복되는 조건은 최상단에 걸어주는게 좋습니다!
최상단에 해당 조건을 걸어주면 최하단 [아무날짜도 선택되지않은 경우] return true만 해주고, 나머지 코드에 해당 조건을 제외시킬수있습니다!

2023-11-07 08:59 UTC, pepperdad commented on src/create/components/ScheduleTab.tsx
> +const tabItems = [
확인했습니다! :)

2023-11-07 09:01 UTC, pepperdad commented on src/create/components/InputCalender.tsx
> +            onChange={(newDate: any) => handleDateChange(newDate)}
확인했습니다 :)

2023-11-07 09:06 UTC, pepperdad commented on src/create/components/Create.tsx
> +          card.title.toLowerCase().includes(title.toLowerCase())
확인했습니당 :)

2023-11-07 09:14 UTC, pepperdad commented on src/create/components/Create.tsx
> +  // date, tab, title 이 바뀔 때마다 필터링 진행
이 부분은 제가 기획쪽 체크를 못했던 것 같습니다! 기존 디자인 화면에서는 찾기 버튼이 없었는데, 지금 확인해보니 생겼습니다! 
필터링말고 찾기버튼을 누르면 쿼리를 날리는 방식으로 수정하면 될 것 같네요! 감사합니다 ㅎㅎ

2023-11-08 12:52 UTC, pepperdad commented
다시 확인 부탁드립니다! 
Review 남겨주신 것들 수정 및 기존의 일정 만들기 1 페이지 -> 모든 일정 페이지로 수정하고, 내 일정 페이지의 헤더와 탭 추가하였습니다.
PR이 조금 길어져서 Approve 시, merge 후 다시 기능별 브랜치 파서 작업 후 PR 올리겠습니다.

2023-11-16 16:36 UTC, NacreousCloud commented on src/schedule/components/ScheduleTab.tsx
> +        {tabItems.map((tab, i) => (
```suggestion
        {tabItems.map(({title}, i) => (
```

가독성을 위한 취향차이긴하지만 map 매개변수를 구조분해로 받는다면 아래 코드들에서 `tab.title`을 title로만 사용할수 있습니다!

2023-11-16 17:17 UTC, NacreousCloud commented on src/schedule/components/All.tsx
> +    // TODO: API 요청 추가 ??? 아님 프론트에서 다시 필터 ??? <- 확인해야 함
보통 검색은 프론트 필터링 없이 api 요청으로만 이뤄집니다!

2023-11-16 17:20 UTC, NacreousCloud commented on src/schedule/components/All.tsx
> +  const filteredInTab = (tab: string, dataList: CardItemType[]) => {
위 답변이 해당 함수에도 적용됩니다! api 요청을 위해 onClickSearch 내부 searchData 에 status 등을 추가하는 방식으로 추후 수정되어야할거같아요! 지금 당장은 작업하지않아도 되니 참고만 해주세요!

2023-11-16 17:23 UTC, NacreousCloud commented on src/schedule/components/AllContent.tsx
> +  const onClickMySchedule = () => setIsMySchedule((prev) => !prev);
내가 만든 일정만 체크하는것도 비슷할겁니다! 필터링하는 로직은 검색 api 쏠때 파라미터로만 추가하면될것같아요!

2023-11-16 17:24 UTC, NacreousCloud approved these changes
확인했습니다! 추가사항이나 따로 이상이 없다면 머지 해주세요~ 고생하셨습니다!

2023-11-20 16:26 UTC, NacreousCloud approved these changes
ACK

2023-11-20 16:27 UTC, merged