Feat: 마이페이지 타이머 로직 수정
Project-Catcher/catcher-web pull request #34
Opened 2023-11-05 16:34 UTC by Choi-Jinwook

## 변경사항
- 도영님이 구현하신 타이머 적용
- callType에 따른 타이머 위치 관리
- 하다보니 아이디/비밀번호 찾기 페이지도 적용했습니다.. 브랜치가 같은 점 너른 양해 부탁드립니다
## 테스트
- http://localhost:3000/mypage
- http://localhost:3000/findidpw

2023-11-06 01:18 UTC, pepperdad requested changes
고생하셨습니다👍  코멘트 한 번 확인해주세요!

2023-11-06 01:18 UTC, pepperdad commented on src/mypage/components/UpdateProfile.tsx
> +  const handleNickName = (nickname: string) => {
[Lv2] 폼의 state를 관리하는 함수를 각각 만드신 이유가 따로 있을까요? 
아니라면 한 함수 내에서 인자를 통해서 필드를 구분하는 방식으로 처리할 수 있을 것 같습니다!

2023-11-06 01:18 UTC, pepperdad commented on src/shared/components/TimerWithButton.tsx
> +          {!isAuthNumValidate && (
[Lv3] 또한, 컴포넌트 내부에 인증번호와 authNum을 체크하는 로직도 추가되어야 할 것 같습니다!
또한, 인증 성공 렌더링이 추가되어야 할 것 같습니다!

2023-11-06 06:33 UTC, Choi-Jinwook commented on src/mypage/components/UpdateProfile.tsx
> +  const handleNickName = (nickname: string) => {
```typescript
  const handleAnswer = (answer: Partial<MyInfoModify>) => {
    setAnswer((prev) => ({ ...prev, ...answer }));
  };

  const handleFormData = (key: string, value: string) => {
    handleAnswer({ [key]: value });
  };
```
이런 식으로 말씀하시는건가요?? 이 방식은 key에 오타 등 이슈가 생길 경우 디버깅이 힘들어서 다른 좋은 방법이 있다면 추천부탁드립니다!!

2023-11-06 06:38 UTC, Choi-Jinwook commented on src/shared/components/TimerWithButton.tsx
> +          {!isAuthNumValidate && (
인증 성공 렌더링은 정목님이랑 이야기해봤는데 필요 없을 것 같아서 제외했습니다!
저희가 인증 확인 버튼이 따로 없고 다음 프로세스로 가는 버튼을 눌렀을 때 인증이 성공했다면 바로 넘어가는 형태이기 때문에 인증 성공 문구는 굳이 넣을 필요가 없을 것 같아서요!!

그리고 인증번호를 체크하는 로직은 6자리 숫자인지 검증하는
```typescript
isAuthNumValidate = checkAuthNumValidate(answer.authNum)
```
를 props로 받아서 처리했습니다! 이 부분은 현재 폼에서부터 쭉 내려오는 형태입니다
인증번호를 체크하는 로직은 다음 프로세스로 가는 버튼을 눌렀을 때 api를 쏠 예정이라 다음 프로세스로 가는 버튼과 함께 있어야 할 것 같아서 이렇게 했습니다!
혹시 더 좋은 아이디어가 있을까요??

2023-11-08 14:14 UTC, NacreousCloud requested changes
확인했습니다! 코멘트 확인부탁드릴게요~

2023-11-08 14:14 UTC, NacreousCloud commented on src/shared/utils/index.ts
> +  const regexEmail = /^[a-z0-9]+(\.[a-z0-9]+)*@[a-z]+\.[a-z]{2,3}$/;
[Lv3] 해당 정규식이면 이메일에 대문자가 허용되지않습니다! 정규식 수정이 필요할것같아요.

추가) 아주 예전에 말씀드렸던 이메일 표준 형식에 대한 레퍼런스를 드디어 발견해서 같이 공유드립니다!
https://ko.wikipedia.org/wiki/%EC%A0%84%EC%9E%90_%EC%9A%B0%ED%8E%B8_%EC%A3%BC%EC%86%8C
정확히는 [RFC 5322](https://tools.ietf.org/html/rfc5322) 규약이 표준이지만, 이렇게되면 기준이 너무 복잡하기도해서 범용적인 부분만 가져오거나, 간소화를 해야할것같아요. 이건 기획팀과 정책상의가 필요할것같습니다.

2023-11-08 14:14 UTC, NacreousCloud commented on src/mypage/components/BoxLabel.tsx
👍👍👍

2023-11-08 14:14 UTC, NacreousCloud commented on src/mypage/components/MypageMainMenu.tsx
> +  onClick?: () => void;
```suggestion
   onClick?: VoidFunction;
```

[Lv1] () => void; 형식은 VoidFunction으로 표현가능합니다!

2023-11-08 14:14 UTC, NacreousCloud commented on src/mypage/components/MypageSubMenu.tsx
> +  onClick: () => void | ((url: string) => void);
```suggestion
  onClick: VoidFunction;
```

[Lv2] ((url: string) => void) 형식은 사용되지않는것같은데 추가하신 이유가 있을까요? 없으면 삭제하는게 나아보입니다!

2023-11-08 14:14 UTC, NacreousCloud commented on src/mypage/components/MypageSubMenu.tsx
> +      onClick: () => handleRoute("/notice"),
```suggestion
      onClick: () => push("/notice"),
```

[Lv2] push만 사용해도 될것같습니다!

2023-11-08 14:14 UTC, NacreousCloud commented on src/mypage/components/UpdateProfile.tsx
> +  const handleNickName = (nickname: string) => {
진욱님의 답변에 해당 방식을 보완해보자면, key의 타입을 명시해주는 방법이 있습니다!

```js
  const handleAnswer = (answer: Partial<MyInfoModify>) => {
    setAnswer((prev) => ({ ...prev, ...answer }));
  };

  const handleFormData = (key: keyof MyInfoModify, value: string) => {
    handleAnswer({ [key]: value });
  };
```


`MyInfoModify`의 키값만 타입으로 받으면 vsc에서 자동완성 및 타입체크를 해주기때문에 오타로 인한 휴먼에러를 방지할수있습니다!

이거랑 별개로, 지금 구조(state를 각각 관리하는방식)를 개선한다면 useReducer를 사용하는 방식도 사용할수있습니다!
상태를 한곳에서 관리하는데, 한번 확인해보시는걸 추천드려요~
예시 링크 : https://velog.io/@rkio/React-useReducer%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC

2023-11-08 23:33 UTC, merged