Feat: 일정 만들기 페이지
Project-Catcher/catcher-web pull request #40
Opened 2023-11-15 14:53 UTC by Choi-Jinwook

## 변경사항
- Figma 일정만들기_3 부분까지 완료했습니다.

## 테스트
- localhost:3000/create-schedule

## Notice
- 이후 추가되는 기능들은 페이지 - 컴포넌트 단위로 새로 브랜치를 파서 현재 feat/makeplan 브랜치로 pr 올릴 예정입니다.

## TODO
- 7일간 보지 않기 체크 후 새로 만들기 or 이어서 작성하기 클릭 시 API 연동
- 이미지 선택 모달
- 일정 시작일~종료일 및 장소 선택 모달 or 아래에 달력/장소 요소 추가 중 뭐로 관리할지 협의
- 새로고침, 뒤로가기 시 입력 사항이 있다면 "변경사항이 있어요" 컨펌

2023-11-19 09:27 UTC, NacreousCloud requested changes
고생하셨습니다! 코멘트 확인 부탁드립니다!

2023-11-19 09:27 UTC, NacreousCloud commented on src/create-schedule/components/Template.tsx
> +  const content = [
[Lv2] Check: 임시 데이터. constants 쪽으로 빼거나, mock api 형식으로 넘기는 방식을 추가하는것이 좋아보입니다.

2023-11-19 09:27 UTC, NacreousCloud commented on src/shared/utils/tag.ts
> +  tagArray.forEach((_tag) => {
```suggestion
  if (tagArray.includes(tag)) throw new Error("태그 중복");
```

2023-11-19 09:27 UTC, NacreousCloud commented on src/create-schedule/components/DateCityInput.tsx
> +            value={answer[answerType!]}
[Lv2] 삼항 조건식으로 나뉘어지는 값이 이 `value` 뿐인것같은데

```
          <DateCityHandler callType={callType} />
          <input
            readOnly
            className="w-[301px] h-[55px] border border-[#E0E0E0] rounded-[5px] px-[19px]"
            type="text"
            placeholder={placeholder}
            value={callType.includes("date") ? answer[answerType!] : answer.city}
          />
```
이렇게 작성하는건 어떨까요?

2023-11-19 09:27 UTC, NacreousCloud commented on src/shared/recoil/planTitle.tsx
[Lv3] 이부분 타입에러 발생하고있습니다! string값을 사용한다면 atom의 타입이 PlanTitle 이나 PlanSubTitle 타입이면 안될것같아요!

2023-11-19 09:27 UTC, NacreousCloud commented on src/create-schedule/components/RemainChar.tsx
> +  const { title } = useRecoilValue(scheduleAnswers);
[Lv2] `RemainChar`바로 상위에서 `scheduleAnswers`를 사용하고있는데 여기서 또 가져오는건 불필요해보입니다! props로 받는건 어떨까요?

2023-11-19 09:27 UTC, NacreousCloud commented on src/create-schedule/components/WritingPlanExisted.tsx
[Lv1] 이 컴포넌트는 어떤 용도인가요?

2023-11-19 09:27 UTC, NacreousCloud commented on src/create-schedule/components/SelectMainImage.tsx
> +  const { openModal } = useModal(); // TODO: unsplash modal
[Lv2] 제가 작업해둔 thumbnail Selector를 적용하시면 될거같습니다! 추가한 이미지를 적용하는것은 modals-test 파일 내부를 참고해주세요!

2023-11-19 09:30 UTC, NacreousCloud commented
추가로, 컴플릭트도 발생하고있어서 develop pull 한번 받고 충돌관리 한번 해주시면 좋겠습니다!

2023-11-20 06:38 UTC, pepperdad commented on src/shared/components/ScheduleCard.tsx
> +        {content.map((_content, index) => (
[Lv1] `{content.map((_content, index) => (` 이 부분에서 content 배열에서 받은 각 요소를 _content 라고 네이밍 하셨는데, 이 부분은 요소의 이름은 배열의 변수명 앞에 _ 를 붙인다던지 혹시 따로 컨벤션이 있는걸까요!? 잘 몰라서 여쭤봅니다!

2023-11-20 06:40 UTC, pepperdad reviewed
확인했습니다! 고생하셨습니다 ~
코멘트만 확인 부탁드릴게요!

2023-11-20 16:22 UTC, Choi-Jinwook commented on src/shared/components/ScheduleCard.tsx
> +        {content.map((_content, index) => (
저도 컨벤션이 있다거나 유래는 몰랐는데 이번에 찾아보니까 과거에 C, C++에서 사용하던 스코프 구분을 위한 표기법이라 합니다!
지역변수를 구분짓고 싶을 때 사용하는데 보통 변수의 네이밍이 겹칠 때 사용합니다!
```typescript
// 공통 input이라 가정
const [value, setValue] = useState("")
const handleInput = (_value: string) => {
  setValue(_value)
}
```
간단한 예시로 이런게 있습니다!

2023-11-20 16:25 UTC, Choi-Jinwook commented on src/create-schedule/components/WritingPlanExisted.tsx
해당 컴포넌트는 작성중이던 일정 이어서 작성하기를 눌렀을 때 사용하려고 했었던 것 같습니다. 생각해보니 임시저장된 데이터만 불러오면 되는거라 만들어놓고 깜빡한 것 같습니다! 삭제하도록 하겠습니다

2023-11-20 16:27 UTC, pepperdad commented on src/shared/components/ScheduleCard.tsx
> +        {content.map((_content, index) => (
아하! 감사합니다 ㅎㅎ

2023-11-21 13:48 UTC, NacreousCloud commented on src/shared/components/ScheduleCard.tsx
> +        {content.map((_content, index) => (
추가로 첨언 드리자면, js에서 변수명에 _를 붙이는 경우가 하나 더 있습니다! 이전에는 클래스의 형태로 컴포넌트를 구성했는데, 내부 private variable이라는것을 명시하기 위해 변수명 앞에 _ 를 붙이곤 했습니다. (물론 접근 자체는 가능하기때문에 암묵적인 표기에 가까웠습니다). 요즘은 클래스로 사용하지않기 때문에 굳이 사용하진않지만 private를 명시하기위해 종종 사용하기도 하는것같아요.

진욱님이 말씀하신 의도로도 사용됩니다! 그래서 언더바가 들어가는 경우는 보통 이 두가지로 유추하곤 합니다. 이외에 사용한다면 오히려 의도를 알수없어서 헷갈리기때문에 코멘트가 달릴수도있으니 참고해주세요!

2023-11-22 05:10 UTC, Choi-Jinwook commented on src/create-schedule/components/DateCityInput.tsx
> +            value={answer[answerType!]}
이 부분 느낌표 사용에 대해 궁금한 부분이 있습니다! answerType이 optional prop이라 undefined일 수 있어 느낌표를 추가했는데 느낌표는 아래 코드와 같이 작성해서 최대한 지양하는게 좋을까요?
```typescript
value={
  answerType && callType.includes("date")
    ? answer[answerType]
    : answer.city
}
```

2023-11-22 05:14 UTC, Choi-Jinwook commented on src/create-schedule/components/RemainChar.tsx
> +  const { title } = useRecoilValue(scheduleAnswers);
전역 상태관리를 사용하니까 설계 단계에서 잠깐 놓치면 이런 일이 자주 발생하는 것 같습니다! 조금 더 신경쓰도록 하겠습니다!

2023-11-22 05:56 UTC, Choi-Jinwook commented
요청사항 수정 완료했습니다! 확인 한번씩 부탁드릴게요!
@NacreousCloud

2023-11-22 15:25 UTC, NacreousCloud commented on src/create-schedule/components/DateCityInput.tsx
> +            value={answer[answerType!]}
네네! 느낌표는 optional이라도 확실하게 데이터가 들어온다는 보장이 있을때만 사용하는것이 좋습니다. 잘하셨어요!

2023-11-22 15:47 UTC, NacreousCloud approved these changes
확인했습니다! 코멘트 추가로 달아놓은것은 지금 PR에 추가로 반영하셔도되고, 다음 PR에 반영하셔도됩니다!

2023-11-22 15:47 UTC, NacreousCloud commented on src/create-schedule/components/RemainChar.tsx
이제 보니 `RemainChar`의 title이 input으로 받는다면 state를 굳이 사용하지않아도될것같습니다!

```typescript
interface RemainCharProps {
  title: string;
}

const LENGTH_LIMIT = 40; // PlanTitleInput 에 두고 input maxLength에 같이 쓰면 관리포인트가 줄어들어서 좋을거같습니다
const RemainChar = ({ title }: RemainCharProps) => {
  const remainChar = LENGTH_LIMIT - title.length;

  return (
    <div className="text-[12px] text-[#8D8D8D] font-medium -tracking-[0.01em]">
      {remainChar < 0 ? 0 : remainChar}자 남음
    </div>
  );
};

export default RemainChar;
```

쓰다보니 추가로 생각이 드는데, input에 입력될때마다 렌더링이 될테니 아예 RemainChar를 빼고 PlanTitleInput에 합쳐도 좋을거같습니다! 이건 급한 수정사항은 아니니 지금 반영해주셔도되고, 다음 PR에 반영하셔도됩니다!

2023-11-22 15:47 UTC, NacreousCloud commented on src/create-schedule/components/SelectMainImage.tsx
[Lv1] 선택된 이미지를 렌더링하는 부분은 기획에 있을까요?? TODO로 선택한 이미지도 렌더링하도록 개선 부탁드립니다!

2023-11-22 15:47 UTC, NacreousCloud commented on src/shared/recoil/planTitle.tsx
[Lv2] 리코일 이 값은 어디에서 사용되는건가요?? 찾아봤을때 호출하는곳은 안보였는데, atom이 PlanTitle 형식이라면, create-schedule/constants 에 있는 TITLE과 SUBTITLE만 import해서 사용해도될거같습니다!

2023-11-24 14:45 UTC, Choi-Jinwook commented on src/shared/recoil/planTitle.tsx
원래 Title 컴포넌트 안에서 제목을 관리하려 했었으나 작업을 진행하면서 굳이 그럴 필요는 없다고 생각이 들어 만들어놓고 사용을 하지 않았습니다! 삭제하도록 하겠습니다

2023-11-24 14:45 UTC, merged