Feat: 내 일정 페이지 구현
Project-Catcher/catcher-web pull request #41
Opened 2023-11-19 12:05 UTC by pepperdad

# 구현사항
> 내 일정 페이지
- 메인
- 모든 일정
- 모집 일정
- 참여 신청 일정
- 임시 저장
- 나만의 아이템

# 테스트
- localhost:3000/schedule
- localhost:3000/schedule/all
- localhost:3000/schedule/recruit
- localhost:3000/schedule/participate
- localhost:3000/schedule/temporary
- localhost:3000/schedule/items

# TODO
- 라우팅 로직 추가
- 삭제, 승인 등 요청 로직 추가
- ScheduleCardProp 정리 필요
- 무한 스크롤 로직 추가

2023-11-21 07:09 UTC, Choi-Jinwook requested changes
고생하셨습니다!! 코멘트 한번씩 확인부탁드립니다!

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/MyScheduleContent.tsx
> +    <div className="w-3/5 pt-10">
<img width="576" alt="image" src="https://github.com/Project-Catcher/catcher-web/assets/79634156/a2b424be-c728-4b92-9652-0f8504389989">

[Lv3] 현재 넓이에 따라 해당 이미지와 같은 버그가 발생합니다! width를 %가 아닌 고정적인 px로 주셔야 할 것 같습니다.

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/ScheduleSmallCard.tsx
> +          </div>
[Lv2] 이 부분 함수가 받아오는 파라미터도 MouseEvent<HTMLDivElement>로 동일하고 구조도 비슷해서 배열로 만들고 map으로 처리하면 깔끔할 것 같습니다!

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/ScheduleHeader.tsx
>            onClick={() => router.push(tab.path)}
[Lv1] push 함수만 사용하는 것이라면
```typescript
const { push } = useRouter();
```
과 같이 사용할 수 있습니다!

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/MyScheduleContent.tsx
> +  >(defaultParticipateList);
[Lv3] 현재 초기 상태에 대한 핸들링이 존재하지 않아 카드를 삭제해도 캐러셀에 등장하는 이슈가 있습니다. 현재 구조를 유지하려면 핸들링 함수를 추가해주셔야 할 것 같습니다! 혹시 다가오는 일정, 모집 중, 참여 신청 부분에 대해 setState를 사용하지 않으신 이유가 있으실까요?

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/All.tsx
>            />
[Lv2] 현재 cardList, setCardList는 ScheduleContent 내부에서만 사용되고 있습니다. 의도된 부분이 아니라면 cardList에 대한 상태를 ScheduleContent 안으로 옮길 방법은 없을까요?

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/All.tsx
>    });
[Lv2] 현재 이 부분은 ContentFilter 컴포넌트에서만 사용되고 있어 All 컴포넌트의 자식 컴포넌트로 넣을 수 있을 것 같습니다!

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/Items.tsx
> +  const [title, setTitle] = useState("");
[Lv2] 이 부분도 Items 컴포넌트의 자식 컴포넌트로 넣을 수 있을 것 같습니다! 탭이 같이 리렌더링될 이유는 없을 것 같아요

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/Items.tsx
> +    setTab(tab as TabType);
[Lv2] tab을 string 말고 TabType으로 지정해주면 as를 사용하지 않아도 될 것 같습니다!

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/Participate.tsx
> +  });
[Lv2] 이 부분도 의도된 부분이 아니라면 분리가 가능할 것 같습니다!

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/Recruit.tsx
> +  });
[Lv2] 이 부분도 의도된 부분이 아니라면 분리가 가능할 것 같습니다!

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/Temporary.tsx
> +  });
[Lv2] 이 부분도 의도된 부분이 아니라면 분리할 수 있을 것 같습니다!

2023-11-21 07:09 UTC, Choi-Jinwook commented on src/schedule/components/ContentFilter.tsx
> +      <div className="mr-2 text-sm font-light text-zinc-800">일정 제목</div>
<img width="957" alt="image" src="https://github.com/Project-Catcher/catcher-web/assets/79634156/c732f3cc-e809-4a65-bfbd-f6b034f7cf70">

[Lv3] 현재 해당 사진처럼 넓이가 변해도 검색창의 넓이는 고정되어있는 이슈가 있습니다! 의도된 부분이 아닌 것 같은데 수정 부탁드립니다!

2023-11-22 13:12 UTC, pepperdad commented on src/schedule/components/MyScheduleContent.tsx
> +    <div className="w-3/5 pt-10">
감사합니다 :)

2023-11-22 13:12 UTC, pepperdad commented on src/schedule/components/ScheduleSmallCard.tsx
> +          </div>
좋습니다!

2023-11-22 13:21 UTC, pepperdad commented on src/schedule/components/Items.tsx
> +    setTab(tab as TabType);
이 부분에서, onClickTab이 ScheduleTab의 props로 전달받는 상황입니다. TabType으로 지정해주면 ScheduleTab의 props타입에서 타입이 안맞아 수정하게 되는데, 하나의 컴포넌트에서 관리하다보니 아래와 같이 TabType으로 넣어줘야하는 상황입니다.

```
type TabType =
  | "전체"
  | "진행 예정"
  | "진행중/완료 일정"
  | "승인 대기 중"
  | "승인 완료"
  | "승인 거절"
  | "모집 중/예정"
  | "모집 완료";

interface ScheduleTab {
  tabTitle: string;
  tabItems: Record<"title", TabType>[];
  currentTab: string;
  onClickTab: (tab: TabType) => void;
}
```
이렇게 들어가면 onClick을 전달하는 컴포넌트 쪽의 type도 `const onClickTab = (tab: TabType) => {` 이렇게 수정되는데, 예를 들어, 전체 탭만 있는 페이지의 경우에도 진행 예정이나, 승인 대기 중과 같은 다른 탭의 type들이 들어올 수 있는 상황이라 현재는 타입 단언을 해준 상황입니다. 이 경우에는 따로 타입 단언을 하는 게 좋은 것 같아서 지금 처럼 string의 타입 단언으로 구현해놓은 상황입니다. 
전체 타입으로 관리하는 게 좋을까요?

2023-11-22 13:26 UTC, pepperdad commented on src/schedule/components/All.tsx
>            />
내부 탭이 바뀜에 따라, cardList의 항목이 필터링 되어야 할 것 같아서 탭과 같은 위치에 두었습니다!

2023-11-22 13:36 UTC, pepperdad commented on src/schedule/components/All.tsx
>            />
cardList가 tab, title, date에 따라서 필터링 되는데, API 요청을 통해 가져온다면, 같은 위치에 있는 것이 맞는 것 같아 하위로 내리지는 않았습니다!

2023-11-22 13:42 UTC, pepperdad commented on src/schedule/components/ScheduleHeader.tsx
>            onClick={() => router.push(tab.path)}
확인했습니다:) 지금 경우는 className에 asPath 를 사용하고 있습니다!

2023-11-22 14:26 UTC, Choi-Jinwook commented on src/schedule/components/Items.tsx
> +    setTab(tab as TabType);
아 이런 이슈가 있었군요! 해당 컴포넌트에서만 확인해서 놓친 부분이네요
지금 구조에서는 현재 방식이 더 깔끔할 것 같습니다. 조금 생각을 해 봤는데 이거 해결하려면 제 실력으로는 구조를 좀 많이 뜯어고쳐야 할 것만 같아요

2023-11-26 07:46 UTC, NacreousCloud requested changes
확인했습니다~ 코멘트 확인 부탁드려요~

2023-11-26 07:46 UTC, NacreousCloud commented on src/modalContent/RecruitManage.tsx
> +  noCallback: () => void;
```suggestion
  noCallback: VoidFunction;
```

2023-11-26 07:46 UTC, NacreousCloud commented on src/schedule/context/TabContext.ts
> +export const TabContext = createContext<string | null>(null);
[Lv1] `TabContext`는 어떻게 사용되나요?? TabContext를 사용하는곳이 `CardStatus` 밖에 안보이는데 이부분은 추후 작업 예정인건가요?

2023-11-26 07:46 UTC, NacreousCloud commented on src/schedule/components/CardStatus.tsx
> +  ) : null;
[Lv2] 맨 마지막 조건 제외하고 return 되는 컴포넌트들이 다 똑같은데 굳이 이렇게 분기처리할 필요가 없어보입니다!

2023-11-26 07:46 UTC, NacreousCloud commented on src/schedule/components/ItemCard.tsx
[Lv2] mock 데이터를 생성해서 사용할수있도록 해주는게 좋을것같습니다!

2023-11-26 07:46 UTC, NacreousCloud commented on src/schedule/components/MyScheduleContent.tsx
> +  const [temporaryCardList, setTemporarayCardList] = useState<CardItemType[]>(
사소한 부분이지만 오타가 있습니다ㅎㅎ
```suggestion
  const [temporaryCardList, setTemporaryCardList] = useState<CardItemType[]>(
```

2023-11-26 07:46 UTC, NacreousCloud commented on src/schedule/components/MyScheduleContent.tsx
> +            marked={card.marked}
```suggestion
           {temporaryCardList.map((card, i) => (
          <ScheduleCard
            cardType={"temporary" as cardType}
            scheduleType={"my" as scheduleType}
            key={`card-${i}`}
            idx={i}
            onClickDelete={onClickDelete}
            {...card}
          />
        ))}
```
[Lv2] 속성이 동일하다면 스프레드 연산자로 대체할수있습니다!

2023-11-26 07:46 UTC, NacreousCloud commented on src/schedule/components/ScheduleWrapper.tsx
> +  children: React.ReactNode;
```suggestion
interface ScheduleWrapperProps extends PropsWithChildren {}
```

[Lv1] PropsWithChildren 을 사용하면, 이후 추가될 props만 넣을수있도록 인터페이스 구성할수있습니다!

2023-11-26 07:46 UTC, NacreousCloud commented on src/schedule/components/TemporaryCard.tsx
> +  handleDeleteToggle: () => void;
```suggestion
  handleDeleteToggle: VoidFunction;
```

2023-12-01 12:45 UTC, pepperdad commented on src/schedule/components/MyScheduleContent.tsx
> +  >(defaultParticipateList);
msw로 데이터 불러와서 setState 사용해서 관리해두었습니다! 코드 보시고 이렇게 말씀하는 게 맞는지 확인 부탁드려요!

2023-12-01 12:48 UTC, pepperdad reviewed
## 변경사항
- 스크랩 페이지 추가
- MSW로 데이터 요청
- 코드 리뷰 사항들 반영

2023-12-01 13:45 UTC, pepperdad commented on src/schedule/context/TabContext.ts
> +export const TabContext = createContext<string | null>(null);
Tab이 변경 될 때 마다 CardStatus를 변경하기 위해서, useEffect에서 의존성 배열에 사용하려고 TabContext를 도입하긴 했는데... 이 부분이 제가 생각하는데로 동작을 하지 않네요. 제가 알기로는 이렇게 tab을 context에서 불러왔을 때, tab이 변경될 때 마다 useEffect가 실행되야할 것 같은데, 그렇게 동작을 안하고 있는 상태입니다. 그래서 현재 CardStatus 컴포넌트 useEffect의 의존성 배열에 여러 인자들이 들어가 있는데, 그냥 tab도 props로 내리는 게 좋을까요?

2023-12-03 08:59 UTC, NacreousCloud commented on src/schedule/context/TabContext.ts
> +export const TabContext = createContext<string | null>(null);
말씀하신 내용이 좀 헷갈리는데 context에서 tab을 가져왔을때 useEffect가 실행되지않나요?? 이부분 한번 정리해서 리뷰해주실수있으면 좋겠습니다!

2023-12-03 09:01 UTC, NacreousCloud approved these changes
확인했습니다! 코멘트 달아놓은 부분만 반영 부탁드릴게용. 고생하셨습니다!

2023-12-03 09:01 UTC, NacreousCloud commented on src/schedule/components/ScheduleCard.tsx
>          className={`w-[260px] h-[225px] bg-stone-300 border-b border-zinc-400 relatvie`}
[Lv3] 이부분 클래스네임 오타나있습니다!
```suggestion
        className={`w-[260px] h-[225px] bg-stone-300 border-b border-zinc-400 relative`}
```

2023-12-03 15:14 UTC, Choi-Jinwook commented on src/schedule/components/MyScheduleContent.tsx
> +  >(defaultParticipateList);
![image](https://github.com/Project-Catcher/catcher-web/assets/79634156/8655c2f1-cd7d-48bc-aac6-3bd67808c08f)

```typescript
<TitleCardContainer title="다가오는 일정" cardList={onComingCardList} />
```

해당 부분에서 prop으로 cardList를 넘겨주고 TitleCardContainer 컴포넌트 안에서만 삭제 처리를 진행하기 때문에 근본적인 onComingCardList는 변하지 않아 생기는 이슈 같습니다. 삭제 api 요청 시 어떻게 될지는 모르겠으나 현재 구조대로면 useEffect에 의존성을 추가하는 방향으로 진행해도 될 것 같습니다! 아니면 onClickDelete 함수가 각 4가지 리스트의 삭제요청에 대해 반응하는 함수이면 될 것 같습니다!

2023-12-04 15:56 UTC, Choi-Jinwook approved these changes
확인완료했습니다! 캐러셀 부분은 삭제 부분 msw 연동 후 확인 부탁드립니다!

2023-12-06 13:10 UTC, merged