Feat: 일정 찾기 페이지 필터 추가
Project-Catcher/catcher-web pull request #44
Opened 2023-11-22 15:28 UTC by pepperdad

# 구현 사항
> 일정 찾기 페이지
- 일정 찾기 페이지의 좌측 테마, 기간, 예상 경비, 지역, 인원 필터 추가

# 테스트 
- http://localhost:3000/find-schedule

# TODO
- 지역 부분 UI 추가

2023-11-25 17:09 UTC, Choi-Jinwook commented on src/findSchedule/components/ThemeTab.tsx
> +            onClick={() => handleTab(item.title)}
[Lv2] 굳이 handleTab 함수를 만들지 않고 setTheme를 바로 사용해도 될 것 같습니다!

2023-11-25 17:24 UTC, Choi-Jinwook requested changes
고생하셨습니다! 코멘트 한 번씩 확인 부탁드릴게요!!

2023-11-25 17:24 UTC, Choi-Jinwook commented on src/findSchedule/components/ThemeTab.tsx
> +            onClick={() => handleTab(item.title)}
[Lv2] 굳이 handleTab 함수를 만들지 않고 setTheme를 사용해도 될 것 같습니다!

2023-11-25 17:24 UTC, Choi-Jinwook commented on src/findSchedule/components/Page.tsx
> +  const [personnel, setPersonnel] = useState<string>("");
[Lv2] 필터를 하나로 묶어서 관리할 수 있을 것 같습니다!
```typescript
const [filter, setFilter] = useState({
  theme: "전체",
  date: { start: undefined, end: undefined },
  showCalendar: { start: false, end: false },
  expense: "",
  personnel: "",
}
```
이렇게 하나의 객체에서 관리하면 라디오 버튼에 대한 클릭처럼 중복되는 부분은 하나의 함수에서 관리가 가능하고, props로 넘겨줄 때도 {...filter} 처럼 더 깔끔하게 넘겨줄 수 있을 것 같은데 어떻게 생각하시나요??

2023-12-03 09:11 UTC, NacreousCloud approved these changes
LGTM. 코멘트 달아놓은 부분들 확인 부탁드립니다~

2023-12-03 09:11 UTC, NacreousCloud commented on src/findSchedule/components/InputCalendar.tsx
> +          <Calendar value={date || undefined} onClickDay={handleDateChange} />
[Lv2] date의 타입이 이미 `Date | undefined` 라서 `|| undefined`는 안붙여도될것같습니다!

2023-12-03 09:11 UTC, NacreousCloud commented on src/findSchedule/components/Page.tsx
> +  const [personnel, setPersonnel] = useState<string>("");
useReducer로 분리하는것도 한번 제안드려봅니다ㅎㅎ 둘다 성능에 큰 차이는 없으니 선호하시는 방향으로 해보세요!

참고링크 : https://react.vlpt.us/basic/20-useReducer.html

2023-12-07 07:20 UTC, Choi-Jinwook approved these changes
머지후에 추가 기능 구현하시면서 요청사항 반영하는 것 고려해주시면 될 것 같습니다!

2023-12-08 15:13 UTC, merged