Feat: 일정 찾기 페이지 카드, 필터링 로직 추가
Project-Catcher/catcher-web pull request #51
Opened 2023-11-24 16:21 UTC by pepperdad

# 구현 사항
> 일정 찾기 페이지
- 일정 찾기 카드, 키워드, 정렬 UI 추가
- 필터별 필터링 로직 추가, 키워드 검색 로직 추가
- 헤더 라우팅 url 수정, z-index 수정

# 테스트 
- http://localhost:3000/find-schedule

# TODO
- 지역 필터 구현
- 정렬 로직 구현

# 추가사항
- msw 이용해서 SSR로 카드데이터 불러오게 구현했습니다. SSR을 처음 사용해봐서, 혹시 로직에 이상있으면 말씀해주시면 감사하겠습니다.
- 필터 부분은 백에서 API 받아올 것이기 때문에, 전부 구현하지는 않았습니다. 좌측의 테마, 기간, 예상 경비, 인원 필터는 모두 동작하나, 키워드를 통한 필터링은 제목, 내용 부분만 가능하게 해두었습니다.
- msw import 이슈 때문에, 헤더 라우팅 url을 조금 수정해두었습니다. 
  - 일정 찾기 클릭 시, /find-schedule
  - 내 일정 클릭 시, /schedule 으로 라우팅 됩니다.

2023-11-25 17:48 UTC, Choi-Jinwook requested changes
고생하셨습니다!! 코멘트 한 번 확인 부탁드릴게요!!
참고해서 저도 msw 사용해보도록 하겠습니다ㅎㅎ 감사합니다 :D

2023-11-25 17:48 UTC, Choi-Jinwook commented on src/findSchedule/components/Page.tsx
> +  });
[Lv2] 키워드 필터는 현재 ScheduleContent에서만 사용되고 있어서 ScheduleContent 컴포넌트 내부로 넣을 수 있을 것 같습니다!

2023-12-07 07:06 UTC, Choi-Jinwook commented on src/findSchedule/components/Page.tsx
> +  });
생각해보니 이것도 같은 레벨에 있어야겠군요..!

2023-12-07 07:07 UTC, Choi-Jinwook approved these changes
LGTM :)

2023-12-10 05:11 UTC, NacreousCloud approved these changes
리뷰를 해놓고 submit을 안하고있었네요 ㅋㅋㅋ; 확인했습니다! 여기있는 내용들은 인터페이스의 수정, 오타들입니다. 그 중하나는 스타일과 관련이 있으니 수정하시고 바로 머지해주세요! 고생하셨습니다!

2023-12-10 05:11 UTC, NacreousCloud commented on pages/find-schedule/index.tsx
> +    const res = await axios.get(
```suggestion
    const res = await axios.get<CardType[]>(
```
[Lv1] axios 함수 제너릭으로 타입을 적어주면 `res.data`의 타입으로 사용할 수 있고 아래에 타입명시 (`as CardType[]`) 을 뺄수있습니다!

2023-12-10 05:11 UTC, NacreousCloud commented on src/findSchedule/components/Card.tsx
> +      <div className={`w-full h-[170px] bg-stone-300 border-zinc-400 relatvie`}>
```suggestion
      <div className={`w-full h-[170px] bg-stone-300 border-zinc-400 relative`}>
```

2023-12-10 05:11 UTC, NacreousCloud commented on src/findSchedule/components/DurationTab.tsx
> +      <div className="flex gap-x-[10px] flex-wrap mt-3">
```suggestion
      <div className="flex gap-x-2.5 flex-wrap mt-3">
```

2023-12-10 05:11 UTC, NacreousCloud commented on src/findSchedule/components/ExpenseTab.tsx
> +  handleExpenseChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
```suggestion
  handleExpenseChange: ChangeEventHandler<HTMLInputElement>;
```

2023-12-10 05:11 UTC, NacreousCloud commented on src/findSchedule/components/InputCalendar.tsx
> +  date: Date | undefined;
```suggestion
  date?: Date;
```

2023-12-10 05:11 UTC, NacreousCloud commented on src/findSchedule/components/InputCalendar.tsx
> +  handleCalendarClick: () => void;
```suggestion
  handleCalendarClick: VoidFunction;
```

2023-12-10 15:58 UTC, pepperdad commented
#58 에 comment 반영하였습니다!

2023-12-10 15:58 UTC, merged